ACP2E-1186: Document the 'count' and 'scope' introduction
AdobeDocs/commerce-testing pull request #20
Opened 2022-09-13 15:17 UTC by thiaramus

## Purpose of this pull request

This pull request (PR) is to update the integration test guide with the newly introduced parameters for data fixtures

## Affected pages

- https://developer.adobe.com/commerce/testing/guide/integration/attributes/data-fixture/
- https://developer.adobe.com/commerce/testing/guide/integration/attributes/data-fixture-before-transaction/

## Links to related PRs or Jira tickets

- https://jira.corp.adobe.com/browse/ACP2E-1186

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My changes follow the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.

2022-09-13 18:23 UTC, bubasuma requested changes

2022-09-13 18:23 UTC, bubasuma commented on src/pages/guide/integration/attributes/data-fixture.md
> +    DataFixture(string $type, array $data = [], string $count = 1, string $scope = 'default', ?string $as = null)
The current order does not match the constructor signature.
```suggestion
    DataFixture(string $type, array $data = [], ?string $as = null, ?string $scope = null, int $count = 1)
```

I am glad that PHP8 introduced named arguments that allows passing values to optional arguments independently of their positions

2022-09-13 18:23 UTC, bubasuma commented on src/pages/guide/integration/attributes/data-fixture.md
> +      $product3 = $fixtures->get('product3');
no alias will be assigned to the fixtures if the alias is not explicitly defined

2022-09-13 18:23 UTC, bubasuma commented on src/pages/guide/integration/attributes/data-fixture.md
> +   }
```suggestion
   #[
        DataFixture(CategoryFixture::class, ['is_anchor' => 0], 'category1'),
        DataFixture(CategoryFixture::class, ['parent_id' => '$category1.id$'], 'category2'),
        DataFixture(ProductFixture::class, ['category_ids' => ['$category1.id$']])
        DataFixture(ProductFixture::class, ['category_ids' => ['$category2.id$']], count: 2)
    ]
    public function testAddCategoryFilter(): void
    {
        $fixtures = DataFixtureStorageManager::getStorage();
        $category1 = $fixtures->get('category1');
        $category2 = $fixtures->get('category2');
        $collection = $this->collectionFactory->addCategoryFilter($category2);
        $this->assertEquals(2, $collection->getSize());
        $collection = $this->collectionFactory->addCategoryFilter($category1);
        $this->assertEquals(1, $collection->getSize());
    }
```

2022-09-13 19:00 UTC, bubasuma approved these changes

2022-09-13 19:45 UTC, jeff-matthews reviewed
@thiaramus, I haven't done a full editorial review, but I made a couple of suggestions per our Slack conversation to identify the `count` and `scope` parameters as dev-only. This isn't the only way we can do it, but it seemed like the most direct and simple approach. What do you think?

2022-09-13 19:45 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +   -  The optional number of entities of the same kind and configuration should this fixture generate.
```suggestion
   - Available to developers using the [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) branch only. Scheduled for release in 2.4.6.
   -  The optional number of entities of the same kind and configuration should this fixture generate.
```

2022-09-13 19:45 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +   -  The optional store view, website or store group identifier, from which the fixture will generate the entity.
```suggestion
   - Available to developers using the [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) branch only. Scheduled for release in 2.4.6.
   -  The optional store view, website or store group identifier, from which the fixture will generate the entity.
```

2022-09-20 16:54 UTC, jeff-matthews requested changes

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture-before-transaction.md
> +   -  The optional number of entities of the same kind and configuration should this fixture generate.
```suggestion
   -  The optional number of entities of the same kind and configuration that this fixture should generate.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture-before-transaction.md
> +   -  The optional store scope name, from which the fixture will generate the entity.
```suggestion
   -  The optional store scope name from which the fixture will generate the entity.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +At this time, the parameter is only available for Adobe Commerce developer, and will become publicly available with Adobe Commerce 2.4.6 release.
```suggestion
At this time, the parameter is available to developers using the [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) branch only. Scheduled for release in 2.4.6.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +   -  The optional number of entities of the same kind and configuration should this fixture generate.
```suggestion
   -  The optional number of entities of the same kind and configuration that this fixture should generate.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +   -  The optional store view, website or store group identifier, from which the fixture will generate the entity.
```suggestion
   -  The optional store view, website, or store group identifier from which the fixture will generate the entity.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +Sometimes we need to generate several instances of a data fixture with exactly the same configuration.
```suggestion
Sometimes, we need to generate several instances of a data fixture with exactly the same configuration.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +For such cases, we can use the `count` parameter, and set its value to the desired number of instances.
```suggestion
For such cases, we can use the `count` parameter and set its value to the desired number of instances.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +The generated fixtures will be assigned aliases product1, product2 and product3 respectively.
```suggestion
The generated fixtures will be assigned aliases product1, product2, and product3 (respectively).
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +At this time, the parameter is only available for Adobe Commerce developer, and will become publicly available with Adobe Commerce 2.4.6 release.
```suggestion
At this time, the parameter is available to developers using the [2.4-develop](https://github.com/magento/magento2/tree/2.4-develop) branch only. Scheduled for release in 2.4.6.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +If you need to instruct the system to execute a data fixture in the scope of a specific store view, you can set the `scope` parameter value to the valid store view, website or store group identifier.
```suggestion
If you need to instruct the system to execute a data fixture in the scope of a specific store view, you can set the `scope` parameter value to the valid store view, website, or store group identifier.
```

2022-09-20 16:54 UTC, jeff-matthews commented on src/pages/guide/integration/attributes/data-fixture.md
> +In the example below, we create a new store with the `store2` identifier and a product. Then we create a guest cart under the `store2` scope and add a created product to it.
```suggestion
In the following example, we create a new store with the `store2` identifier and a product. Then, we create a guest cart under the `store2` scope and add a created product to it.
```

2022-09-20 18:48 UTC, jeff-matthews approved these changes
@thiaramus, just let me know when you're ready to merge.

2022-10-05 17:43 UTC, thiaramus commented
> @thiaramus, just let me know when you're ready to merge.

It is now ready. Thank you, Jeff!

2022-10-05 17:45 UTC, jeff-matthews approved these changes

2022-10-05 17:46 UTC, merged