Fix wording
AdobeDocs/commerce-testing pull request #65
Opened 2023-09-22 08:57 UTC by sprankhub

## Purpose of this pull request

This pull request (PR) fixes the wording for the `magentoDataFixtureBeforeTransaction` annotation. Fixtures only support PHP script files, but no classes.

## Affected pages

- https://developer.adobe.com/commerce/testing/guide/integration/annotations/

2023-09-22 08:58 UTC, sprankhub commented
Reading through https://developer.adobe.com/commerce/testing/guide/integration/attributes/data-fixture-before-transaction/, I am not sure if my PR is correct :D Maybe it is indeed possible to use classes by now? Then we should maybe make this "to a class, a script file or a method"?

2023-09-25 14:01 UTC, jeff-matthews reviewed
Thanks for the PR @sprankhub. I'm confirming with internal engineers.

2023-09-25 14:16 UTC, thiaramus approved these changes

2023-09-25 14:18 UTC, thiaramus requested changes

2023-09-25 14:18 UTC, thiaramus commented on src/pages/guide/integration/annotations/index.md
> +Data Fixture|`@magentoDataFixture`|`@magentoDataFixture <script_filename> / <method_name>/<fully_qualified_class_name> [as:alias with:{}]`|Points to a file or a method which creates testing entities
```suggestion
Data Fixture|`@magentoDataFixture`|`@magentoDataFixture <script_filename> / <method_name> [as:alias with:{}]`|Points to a file or a method which creates testing entities (fixtures) for test execution. These are applied during the transaction.
```

2023-09-25 14:47 UTC, jeff-matthews commented
@sprankhub, please see/accept the suggestion from @thiaramus and we'll get this merged.

2023-09-26 13:19 UTC, jeff-matthews approved these changes

2023-09-26 13:26 UTC, merged